import React from "react";
import { Car, Users, Clock, ShieldCheck, Mountain, Building2, Plane, Navigation as NavIcon } from "lucide-react";
import { Translations } from "@/data/translations";

export const siteConfig = {
  contact: {
    phoneNumber: "0842908841",
    lineOaUrl: "https://lin.ee/ceodEHa",
    whatsappUrl: "https://wa.me/message/LEZ3ZQMI237NK1",
    facebookUrl: "https://www.facebook.com/songphop652?locale=th_TH",
  },
  getNavLinks: (t: Translations) => [
    { href: "#about", label: t.nav.whyUs },
    { href: "#services", label: t.nav.services },
    { href: "#areas", label: t.nav.areas },
    { href: "#reviews", label: t.nav.reviews },
    { href: "#gallery", label: t.nav.gallery },
    { href: "#articles", label: t.nav.articles },
    { href: "#contact", label: t.nav.contact },
  ],
  whyUsImage: "/assets/images/about/about.webp",
  heroImage: "/assets/images/hero/hero.webp",
  contactBgImage: "/assets/images/contact/contact.webp",
  galleryImages: [
    { src: "/assets/images/gallery/gallery_01.jpg", alt: "Gallery 1", span: "col-span-2 row-span-2", caption: "Premium Vans" },
    { src: "/assets/images/gallery/gallery_02.webp", alt: "Gallery 2" },
    { src: "/assets/images/gallery/gallery_03.webp", alt: "Gallery 3" },
    { src: "/assets/images/gallery/gallery_04.jpg", alt: "Gallery 4", span: "col-span-2" },
    { src: "/assets/images/gallery/gallery_05.jpg", alt: "Gallery 5" },
    { src: "/assets/images/gallery/gallery_06.jpg", alt: "Gallery 6" },
    { src: "/assets/images/gallery/gallery_07.webp", alt: "Gallery 7", span: "col-span-2" },
    { src: "/assets/images/gallery/gallery_08.webp", alt: "Gallery 8", span: "col-span-2" },
    { src: "/assets/images/gallery/gallery_09.webp", alt: "Gallery 9" },
    { src: "/assets/images/gallery/gallery_10.jpg", alt: "Gallery 10" },
    { src: "/assets/images/gallery/gallery_11.webp", alt: "Gallery 11" },
    { src: "/assets/images/gallery/gallery_12.jpg", alt: "Gallery 12" },
    { src: "/assets/images/gallery/gallery_13.jpg", alt: "Gallery 13", span: "col-span-2" },
    { src: "/assets/images/gallery/gallery_14.jpg", alt: "Gallery 14", span: "col-span-2" },
    { src: "/assets/images/gallery/gallery_15.jpg", alt: "Gallery 15" },
    { src: "/assets/images/gallery/gallery_16.jpg", alt: "Gallery 16" },
  ],
  tripImages: [
    { src: "/assets/images/trip/trip_01_pattaya.jpg", alt: "Trip 1", caption: "Pattaya" },
    { src: "/assets/images/trip/trip_02_chiang_mai.jpg", alt: "Trip 2", caption: "Chiang Mai" },
    { src: "/assets/images/trip/trip_03_phuket.jpg", alt: "Trip 3", caption: "Phuket" },
    { src: "/assets/images/trip/trip_04_ayutthaya.jpg", alt: "Trip 4", caption: "Ayutthaya" },
    { src: "/assets/images/trip/trip_05_kanchanaburi.jpg", alt: "Trip 5", caption: "Kanchanaburi" },
    { src: "/assets/images/trip/trip_06_khao_kho.jpg", alt: "Trip 6", caption: "Khao Kho" },
    { src: "/assets/images/trip/trip_07_hua_hin.jpg", alt: "Trip 7", caption: "Hua Hin" },
    { src: "/assets/images/trip/trip_08_koh_chang.jpg", alt: "Trip 8", caption: "Koh Chang" },
  ],
  articleImages: {
    "1": "/assets/images/article/article_01.webp",
    "2": "/assets/images/article/article_02.webp",
    "3": "/assets/images/article/article_03.webp",
    "4": "/assets/images/article/article_04.webp",
    "5": "/assets/images/article/article_05.webp",
    "6": "/assets/images/article/article_06.webp",
  } as Record<string, string>,
  featureIcons: [
    <Car key="car" size={28} />,
    <Users key="users" size={28} />,
    <Clock key="clock" size={28} />,
    <ShieldCheck key="shield" size={28} />,
  ],
  serviceImages: [
    "/assets/images/service/service_tour.webp",
    "/assets/images/service/service_seminar.webp",
    "/assets/images/service/service_airport.webp",
  ],
  serviceIcons: [
    <Mountain key="mountain" size={32} />,
    <Building2 key="building" size={32} />,
    <Plane key="plane" size={32} />,
  ],
  areaIcons: [
    <Building2 key="building" size={24} />,
    <NavIcon key="nav" size={24} />,
    <Plane key="plane" size={24} />,
  ],
};
